<?php 
return array(
"Person",
"ID: Resource name",
"ID: URL",
"Description",
"Project",
"Search Criterion",
"Research Questions",
"Item:Resource example",
"Reused resource",
"Resource type",
"Type: Collection",
"Type: Specification",
"Affordance: Is playable?",
"Purpose: Learning",
"Purpose: Research",
"Scope: Temporal",
"Scope: Geographical",
"Scope: Genre",
"Scope: Artist",
"Scope: Formats",
"Scope: MO type",
"Scope: Object type",
"Access: Public",
"Access: license",
"Access: Free/Charged",
"Format: Interoperable?",
"Interface: Human consumption?",
"Interface: API?",
"Interface: SPARQL endpoint?",
"SPARQL endpoint URI",
"Interface: Data Dump?",
"Interface: Is it queryable?",
"Interface: Browsable?",
"Collection: Size",
"Data size",
"Symbolic: Machine readable?",
"Feature: Melody",
"Feature: Harmony",
"Feature: Lyrics",
"Feature: Rhythm",
"Feature: Timbre",
"Feature: Contour/Shape",
"Feature: Structure",
"Feature: Descriptive Metadata",
"Situation/Task",
"Target audience");